[package]
name = "regioncam"
version = "0.1.0"
edition = "2021"

[lib]
name = "regioncam"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.16.1"
nonmax = "0.5.5"
numpy = "0.23.0"
pyo3 = { version = "0.23.4", features = ["extension-module"] }
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
svg_fmt = "0.4.4"
wasm-bindgen = "0.2.100"
